[workspace]
resolver = "2"
members = ["girolle", "girolle_macro", "examples"]

[workspace.dependencies]
serde_json = "1.0.127"
tokio = { version = "1.39.3", features = ["full"] }
serde = { version = "1.0.209", features = ["derive", "rc"] }