[workspace]
resolver = "2"
members = ["girolle", "girolle_macro", "examples"]

[workspace.dependencies]
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
serde = { version = "1.0.216", features = ["derive", "rc"] }
