[package]
name = "girolle"
version = "0.1.0"
edition = "2021"
authors = ["Philippe Llerena <philippe.llerena@gmail.com>"]
description = "a simple command line tool to list frame sequence in friendly way"
readme = "README.md"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.0", features = ["full"] }
lapin = "2.3.1"
serde_json = "1.0.64"
tokio-executor-trait = "2.1.1"
tokio-reactor-trait = "1.1.0"
serde = { version = "1.0.193", features = ["derive"] }
