//! Argument binding for RPC handlers.
//!
//! Maps an inbound [`Payload`] (a mix of positional `args` and
//! keyword `kwargs`) onto a handler's declared parameter list,
//! filling missing positionals from the kwargs by name. Used by the
//! code generated by `#[girolle]` and exposed via
//! [`crate::__macro_support`] for that purpose.

use crate::error::GirolleError;
use crate::payload::Payload;
use serde_json::Value;
use std::collections::HashMap;

fn push_values_to_result(
    service_args: &[&str],
    kwargs: &HashMap<String, Value>,
    start: usize,
    end: usize,
) -> Result<Vec<Value>, GirolleError> {
    service_args[start..end]
        .iter()
        .map(|&arg| {
            kwargs.get(arg).cloned().ok_or_else(|| {
                GirolleError::IncorrectSignature("Key is missing in kwargs".to_string())
            })
        })
        .collect()
}

/// Bind an inbound [`Payload`] to a handler's parameter list.
///
/// Concatenates `args` with the values of `kwargs` looked up by name
/// in declaration order. Errors if the total count doesn't match
/// `service_args.len()` or if a required kwarg is missing.
pub fn build_inputs_fn_service(
    service_args: &[&str],
    data_delivery: Payload,
) -> Result<Vec<Value>, GirolleError> {
    let args_size = data_delivery.args.len();
    let kwargs_size = data_delivery.kwargs.len();
    let service_args_size = service_args.len();

    if service_args_size == args_size + kwargs_size {
        if kwargs_size == 0 {
            return Ok(data_delivery.args);
        }
        let mut result = Vec::with_capacity(service_args_size);
        result.extend(data_delivery.args);
        result.extend(push_values_to_result(
            service_args,
            &data_delivery.kwargs,
            args_size,
            service_args_size,
        )?);
        Ok(result)
    } else {
        Err(GirolleError::IncorrectSignature(format!(
            "takes {} positional arguments but {} were given",
            service_args_size,
            args_size + kwargs_size
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_push_values_to_result_success() {
        let service_args = vec!["arg1", "arg2"];
        let mut kwargs = HashMap::new();
        kwargs.insert("arg1".to_string(), Value::String("value1".to_string()));
        kwargs.insert("arg2".to_string(), Value::String("value2".to_string()));

        let result = push_values_to_result(&service_args, &kwargs, 0, 2);
        assert!(result.is_ok());
        let values = result.unwrap();
        assert_eq!(
            values,
            vec![
                Value::String("value1".to_string()),
                Value::String("value2".to_string())
            ]
        );
    }

    #[test]
    fn test_push_values_to_result_missing_key() {
        let service_args = vec!["arg1", "arg3"];
        let mut kwargs = HashMap::new();
        kwargs.insert("arg1".to_string(), Value::String("value1".to_string()));

        let result = push_values_to_result(&service_args, &kwargs, 0, 2);
        assert!(result.is_err());
        match result {
            Err(GirolleError::IncorrectSignature(msg)) => {
                assert_eq!(msg, "Key is missing in kwargs".to_string());
            }
            _ => panic!("Expected GirolleError::IncorrectSignature"),
        }
    }

    #[test]
    fn test_build_inputs_fn_service() {
        let service_args = vec!["a", "b", "c"];
        let data_delivery = Payload::new()
            .arg(Value::String("1".to_string()))
            .arg(Value::String("2".to_string()))
            .kwarg("c", Value::String("3".to_string()));
        let result = build_inputs_fn_service(&service_args, data_delivery);
        assert!(result.is_ok());
        let result = result.unwrap();
        assert_eq!(result.len(), 3);
        assert_eq!(result[0], Value::String("1".to_string()));
        assert_eq!(result[1], Value::String("2".to_string()));
        assert_eq!(result[2], Value::String("3".to_string()));
    }
}
