//! RpcService side: register methods, subscribe to events, run the
//! dispatch loop.
//!
//! Module map:
//! - [`task`] — `RpcTask`, `RpcHandler`, `EventHandler`, `BoxFuture`
//! - [`context`] — per-delivery `RpcContext` handed to handlers
//! - [`caller`] — `RpcCaller` + core (in-service RPC client capability)
//! - [`dispatcher`] — `EventDispatcher` + core (in-service event capability)
//! - [`args`] — handler argument binding (used by `#[girolle]`)
//! - `runtime` (private) — the async dispatch loop

pub mod args;
pub mod caller;
pub mod context;
pub mod dispatcher;
pub mod task;
mod runtime;

use crate::config::Config;
use crate::error::GirolleError;
use std::collections::HashMap;

use self::runtime::EventSubscription;
pub use self::task::RpcTask;

/// # RpcService
///
/// A long-running RPC service. Build it with [`RpcService::new`],
/// register methods with [`RpcService::register`] and/or event
/// subscriptions with [`RpcService::subscribe`], then call
/// [`RpcService::start`]. `start` blocks the calling thread until the
/// process receives SIGINT.
///
/// ## Example
///
/// ```rust,no_run
/// use girolle::prelude::*;
///
/// #[girolle]
/// fn hello(s: String) -> String {
///     format!("Hello, {}!, by Girolle", s)
/// }
///
/// fn main() {
///     let _ = RpcService::new(Config::default(), "video")
///         .register(hello)
///         .start();
/// }
/// ```
pub struct RpcService {
    conf: Config,
    service_name: String,
    f: HashMap<String, RpcTask>,
    subscriptions: Vec<EventSubscription>,
}

impl RpcService {
    /// Build a new service bound to `service_name`. No methods or
    /// subscriptions are registered yet.
    pub fn new(conf: Config, service_name: &'static str) -> Self {
        Self {
            conf,
            service_name: service_name.to_string(),
            f: HashMap::new(),
            subscriptions: Vec::new(),
        }
    }

    /// Override the service name set at construction time.
    pub fn set_service_name(&mut self, service_name: String) {
        self.service_name = service_name;
    }

    /// Register an RPC method.
    ///
    /// `fn_macro` is typically the constructor function generated by
    /// the [`#[girolle]`](girolle_macro::girolle) attribute macro.
    pub fn register(mut self, fn_macro: fn() -> RpcTask) -> Self {
        let rpc_task = fn_macro();
        self.insert(rpc_task.name, rpc_task);
        self
    }

    fn insert(&mut self, method_name: &'static str, f: RpcTask) {
        let routing_key = format!("{}.{}", self.service_name, method_name);
        self.f.insert(routing_key, f);
    }

    /// Register an async event handler for `<source_service>.events`
    /// with routing key `event_type`.
    ///
    /// Multiple `subscribe` calls coexist with `register` calls on the
    /// same service. A service consisting only of subscriptions (no
    /// RPC methods) is allowed.
    ///
    /// ## Example
    ///
    /// ```rust,no_run
    /// use girolle::prelude::*;
    /// use std::sync::Arc;
    ///
    /// fn main() {
    ///     let _ = RpcService::new(Config::default(), "observer").subscribe(
    ///         "users",
    ///         "user_created",
    ///         Arc::new(|_ctx, payload| {
    ///             Box::pin(async move {
    ///                 println!("event: {}", payload);
    ///                 Ok(())
    ///             })
    ///         }),
    ///     );
    /// }
    /// ```
    pub fn subscribe(
        mut self,
        source_service: &str,
        event_type: &str,
        handler: self::task::EventHandler,
    ) -> Self {
        self.subscriptions.push(EventSubscription {
            source_service: source_service.to_string(),
            event_type: event_type.to_string(),
            handler,
        });
        self
    }

    /// Run the service. Blocks until SIGINT.
    ///
    /// Panics if the service has neither RPC methods nor event
    /// subscriptions registered.
    pub fn start(&self) -> Result<(), GirolleError> {
        if self.f.is_empty() && self.subscriptions.is_empty() {
            panic!("RpcService has neither RPC methods nor event subscriptions");
        }
        runtime::run(
            &self.conf,
            &self.service_name,
            self.f.clone(),
            self.subscriptions.clone(),
        )
    }

    /// All routing keys this service will respond to.
    pub fn get_routing_keys(&self) -> Vec<String> {
        self.f.keys().cloned().collect()
    }

    pub fn get_config(&self) -> &Config {
        &self.conf
    }

    pub fn set_config(&mut self, config: Config) -> Result<(), String> {
        self.conf = config;
        Ok(())
    }
}
