[package]
name = "girolle_macro"
version = "1.0.0"
edition = "2021"
readme = "../README.md"
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.74"
quote = "1.0.35"
syn = { version = "2.0.46", features = ["fold", "full"] }
girolle = { path = "../girolle", version = "1.0.0" }
serde_json = "1.0.110"

[dev-dependencies]
